version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app      # Sync host files
      - /app/node_modules  # Avoid overwriting container deps
    command: npm run dev   # Use nodemon for auto-restart
    environment:
      - NODE_ENV=development

  web_prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node src/app.js
    environment:
      - NODE_ENV=production